steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/civic-summer-280810/demo:$TAG_NAME', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/civic-summer-280810/demo:$TAG_NAME']##project on google cloud
- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=gs://artifacts.civic-summer-280810.appspot.com/deployment.yaml ##storage on google cloud
  - --image=gcr.io/civic-summer-280810/demo:$TAG_NAME
  - --location=asia-northeast1-a
  - --cluster=k8scluster
